version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/core
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: /apps/cli
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: /apps/scanner
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /apps/ui
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
