// SPDX-License-Identifier: GPL-3.0-or-later
package cmd

import (
	"fmt"
	"net"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/spf13/cobra"
)

// timeNow is a seam so tests can pin the timestamp the template prints.
var timeNow = time.Now

// known DoH provider IPs that we recommend blackholing at the firewall
// alongside the DNS-port lockdown. List is intentionally short and
// boring — the v4 anycast addresses every browser and OS uses by
// default. IPv6 equivalents are in the same templates.
var dohProviderIPs = []routerIP{
	{Owner: "Cloudflare", IP4: "1.1.1.1", IP6: "2606:4700:4700::1111"},
	{Owner: "Cloudflare", IP4: "1.0.0.1", IP6: "2606:4700:4700::1001"},
	{Owner: "Google", IP4: "8.8.8.8", IP6: "2001:4860:4860::8888"},
	{Owner: "Google", IP4: "8.8.4.4", IP6: "2001:4860:4860::8844"},
	{Owner: "Quad9", IP4: "9.9.9.9", IP6: "2620:fe::fe"},
	{Owner: "Quad9", IP4: "149.112.112.112", IP6: "2620:fe::9"},
	{Owner: "OpenDNS", IP4: "208.67.222.222", IP6: "2620:119:35::35"},
	{Owner: "OpenDNS", IP4: "208.67.220.220", IP6: "2620:119:53::53"},
	{Owner: "AdGuard", IP4: "94.140.14.14", IP6: "2a10:50c0::ad1:ff"},
	{Owner: "NextDNS", IP4: "45.90.28.0", IP6: "2a07:a8c0::"},
}

type routerIP struct {
	Owner string
	IP4   string
	IP6   string
}

type routerTmplData struct {
	HydraIP     string
	BlockDoHIPs bool
	DoHIPs      []routerIP
}

const pfsenseTemplate = `# HydraDNS firewall rules for pfSense / OPNsense
# Generated by hydra setup-router on {{ now }}
#
# Apply via: Diagnostics > Edit File > /tmp/rules.debug, or via the
# Firewall > Rules UI. Replace LAN with whatever your inside interface
# is named.
#
# Effect: every device on LAN is forced to use {{.HydraIP}} for DNS;
# direct DNS to anywhere else (port 53 or 853) is dropped at the gate.

# 1. Allow HydraDNS itself to make outbound DNS queries
pass out on $WAN proto { tcp udp } from {{.HydraIP}} to any port { 53 853 } keep state

# 2. Allow LAN clients to talk to HydraDNS on 53 and 853
pass in on $LAN proto { tcp udp } from $LAN_NET to {{.HydraIP}} port { 53 853 } keep state

# 3. Drop every other outbound DNS query from the LAN
block in log on $LAN proto { tcp udp } from $LAN_NET to ! {{.HydraIP}} port { 53 853 }
{{- if .BlockDoHIPs }}

# 4. Blackhole well-known public DoH provider IPs on TCP/UDP 443 so
#    a browser cannot reach them even when DNS is locked down.
{{- range .DoHIPs }}
block in log on $LAN proto { tcp udp } from $LAN_NET to {{.IP4}} port 443  # {{.Owner}}
block in log on $LAN proto { tcp udp } from $LAN_NET to {{.IP6}} port 443  # {{.Owner}} (v6)
{{- end }}
{{- end }}
`

const mikrotikTemplate = `# HydraDNS firewall rules for MikroTik RouterOS
# Generated by hydra setup-router on {{ now }}
#
# Paste into the terminal or import via:
#   /import file-name=hydra-firewall.rsc
#
# Replace bridge-lan with your actual LAN bridge name if different.

/ip firewall filter
add chain=forward action=accept src-address={{.HydraIP}} protocol=udp dst-port=53 \
    comment="HydraDNS allowed out :53"
add chain=forward action=accept src-address={{.HydraIP}} protocol=tcp dst-port=53 \
    comment="HydraDNS allowed out :53/tcp"
add chain=forward action=accept src-address={{.HydraIP}} protocol=tcp dst-port=853 \
    comment="HydraDNS allowed out :853"
add chain=forward action=accept dst-address={{.HydraIP}} in-interface=bridge-lan \
    protocol=udp dst-port=53 comment="LAN -> HydraDNS :53"
add chain=forward action=accept dst-address={{.HydraIP}} in-interface=bridge-lan \
    protocol=tcp dst-port=53 comment="LAN -> HydraDNS :53/tcp"
add chain=forward action=accept dst-address={{.HydraIP}} in-interface=bridge-lan \
    protocol=tcp dst-port=853 comment="LAN -> HydraDNS :853"
add chain=forward action=drop in-interface=bridge-lan protocol=udp dst-port=53 \
    comment="Drop other DNS"
add chain=forward action=drop in-interface=bridge-lan protocol=tcp dst-port=53 \
    comment="Drop other DNS/tcp"
add chain=forward action=drop in-interface=bridge-lan protocol=tcp dst-port=853 \
    comment="Drop DoT"
{{- if .BlockDoHIPs }}

# Blackhole public DoH provider IPs on :443
{{- range .DoHIPs }}
add chain=forward action=drop in-interface=bridge-lan dst-address={{.IP4}} \
    protocol=tcp dst-port=443 comment="Block DoH {{.Owner}} {{.IP4}}"
add chain=forward action=drop in-interface=bridge-lan dst-address={{.IP4}} \
    protocol=udp dst-port=443 comment="Block DoH {{.Owner}} {{.IP4}}/udp"
{{- end }}
{{- end }}

/ip firewall nat
add chain=dstnat action=dst-nat to-addresses={{.HydraIP}} to-ports=53 \
    in-interface=bridge-lan protocol=udp dst-port=53 \
    src-address-list=!hydra-skip comment="Force LAN UDP :53 -> HydraDNS"
add chain=dstnat action=dst-nat to-addresses={{.HydraIP}} to-ports=53 \
    in-interface=bridge-lan protocol=tcp dst-port=53 \
    src-address-list=!hydra-skip comment="Force LAN TCP :53 -> HydraDNS"
`

const openwrtTemplate = `# HydraDNS firewall rules for OpenWrt
# Generated by hydra setup-router on {{ now }}
#
# Append to /etc/firewall.user, then run: /etc/init.d/firewall restart
# Assumes the LAN zone is named "lan" and the WAN zone "wan".

# 1. Block direct DNS from LAN to anywhere except HydraDNS
iptables -I FORWARD -i br-lan -p udp --dport 53 -j DROP
iptables -I FORWARD -i br-lan -p tcp --dport 53 -j DROP
iptables -I FORWARD -i br-lan -p tcp --dport 853 -j DROP

# 2. Carve out HydraDNS itself
iptables -I FORWARD -i br-lan -d {{.HydraIP}} -p udp --dport 53 -j ACCEPT
iptables -I FORWARD -i br-lan -d {{.HydraIP}} -p tcp --dport 53 -j ACCEPT
iptables -I FORWARD -i br-lan -d {{.HydraIP}} -p tcp --dport 853 -j ACCEPT

# 3. NAT-redirect any device that ignores DHCP and uses 8.8.8.8 etc.
iptables -t nat -A PREROUTING -i br-lan -p udp --dport 53 \
    ! -d {{.HydraIP}} -j DNAT --to-destination {{.HydraIP}}:53
iptables -t nat -A PREROUTING -i br-lan -p tcp --dport 53 \
    ! -d {{.HydraIP}} -j DNAT --to-destination {{.HydraIP}}:53
{{- if .BlockDoHIPs }}

# 4. Blackhole well-known DoH provider IPs on :443
{{- range .DoHIPs }}
iptables -I FORWARD -i br-lan -d {{.IP4}} -p tcp --dport 443 -j DROP  # {{.Owner}}
iptables -I FORWARD -i br-lan -d {{.IP4}} -p udp --dport 443 -j DROP  # {{.Owner}}/udp
{{- end }}
{{- end }}
`

const asusTemplate = `#!/bin/sh
# HydraDNS firewall rules for ASUS Merlin
# Generated by hydra setup-router on {{ now }}
#
# Save as /jffs/scripts/nat-start, chmod +x, then reboot.
# Requires Merlin (custom firmware), not stock ASUS.

# 1. Block all DNS not destined for HydraDNS
iptables -I FORWARD -i br0 -p udp --dport 53 -j DROP
iptables -I FORWARD -i br0 -p tcp --dport 53 -j DROP
iptables -I FORWARD -i br0 -p tcp --dport 853 -j DROP
iptables -I FORWARD -i br0 -d {{.HydraIP}} -p udp --dport 53 -j ACCEPT
iptables -I FORWARD -i br0 -d {{.HydraIP}} -p tcp --dport 53 -j ACCEPT
iptables -I FORWARD -i br0 -d {{.HydraIP}} -p tcp --dport 853 -j ACCEPT

# 2. Force-redirect outgoing :53 to HydraDNS (catches devices that
#    ignored DHCP and picked their own resolver)
iptables -t nat -I PREROUTING -i br0 -p udp --dport 53 \
    ! -d {{.HydraIP}} -j DNAT --to-destination {{.HydraIP}}:53
iptables -t nat -I PREROUTING -i br0 -p tcp --dport 53 \
    ! -d {{.HydraIP}} -j DNAT --to-destination {{.HydraIP}}:53
{{- if .BlockDoHIPs }}

# 3. Blackhole public DoH provider IPs on :443
{{- range .DoHIPs }}
iptables -I FORWARD -i br0 -d {{.IP4}} -p tcp --dport 443 -j DROP  # {{.Owner}}
iptables -I FORWARD -i br0 -d {{.IP4}} -p udp --dport 443 -j DROP  # {{.Owner}}/udp
{{- end }}
{{- end }}
`

var routerTemplates = map[string]string{
	"pfsense":  pfsenseTemplate,
	"mikrotik": mikrotikTemplate,
	"openwrt":  openwrtTemplate,
	"asus":     asusTemplate,
}

var (
	setupRouterKind        string
	setupRouterHydraIP     string
	setupRouterBlockDoHIPs bool
)

var setupRouterCmd = &cobra.Command{
	Use:   "setup-router",
	Short: "Generate firewall rules for the customer's router that lock DNS to the HydraDNS Pi",
	Long: `Emits a ready-to-paste firewall snippet for the named router that:

  - allows the HydraDNS Pi to query upstreams on :53 and :853
  - allows LAN clients to talk to the Pi on :53 and :853
  - blocks every other outbound :53 / :853 from the LAN, so a device
    that hardcoded 8.8.8.8 cannot bypass HydraDNS
  - optionally blackholes well-known public DoH provider IPs on :443

Snippet is written to stdout. Pipe to a file or paste straight into
the router's config UI. The router is not contacted; this is purely
a code generator so the installer can stage the change off-site.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		kind := strings.ToLower(strings.TrimSpace(setupRouterKind))
		tmplStr, ok := routerTemplates[kind]
		if !ok {
			return fmt.Errorf("unknown router kind %q (supported: pfsense, mikrotik, openwrt, asus)", kind)
		}
		if net.ParseIP(setupRouterHydraIP) == nil {
			return fmt.Errorf("--hydra-ip %q is not a valid IP address", setupRouterHydraIP)
		}

		t, err := template.New(kind).Funcs(template.FuncMap{
			"now": currentDateString,
		}).Parse(tmplStr)
		if err != nil {
			return fmt.Errorf("template parse: %w", err)
		}
		return t.Execute(os.Stdout, routerTmplData{
			HydraIP:     setupRouterHydraIP,
			BlockDoHIPs: setupRouterBlockDoHIPs,
			DoHIPs:      dohProviderIPs,
		})
	},
}

// currentDateString is exposed via the template so the generated
// snippet carries a "this was made on..." trail. Functions defined as
// vars (not consts) so tests can stub if needed.
var currentDateString = func() string {
	return timeNow().Format("2006-01-02")
}

func init() {
	setupRouterCmd.Flags().StringVar(&setupRouterKind, "kind", "",
		"Router type: pfsense, mikrotik, openwrt, asus (required)")
	setupRouterCmd.Flags().StringVar(&setupRouterHydraIP, "hydra-ip", "",
		"LAN IP of the HydraDNS Pi, e.g. 192.168.1.50 (required)")
	setupRouterCmd.Flags().BoolVar(&setupRouterBlockDoHIPs, "block-doh-ips", true,
		"Also blackhole well-known public DoH provider IPs on :443")
	setupRouterCmd.MarkFlagRequired("kind")
	setupRouterCmd.MarkFlagRequired("hydra-ip")
	rootCmd.AddCommand(setupRouterCmd)
}
